package com.airguard.server.service;

import com.airguard.server.model.PlaneData;
import com.airguard.server.model.Runway;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.Arrays;
import jakarta.annotation.PostConstruct;

@Service // אומר ל-Spring: "זה מנהל שירות, שמור עליו"
public class AirSpaceService {

    // הזיכרון החי: מפתח = מזהה מטוס, ערך = נתוני המטוס
    private final ConcurrentHashMap<String, PlaneData> activePlanes = new ConcurrentHashMap<>();

    // רשימת המסלולים בשדה
    private List<Runway> runways = new ArrayList<>();

    // אתחול המסלולים ברגע שהשרת עולה
    @PostConstruct
    public void initRunways() {
        runways.clear();

        // מסלול צפוני - קטן
        runways.add(new Runway("RWY-1", Arrays.asList("Small"),
                new double[]{32.05, 34.83}, new double[]{32.05, 34.93}));

        // מסלול אמצע-צפון - משולב
        runways.add(new Runway("RWY-2", Arrays.asList("Small", "Medium"),
                new double[]{32.03, 34.83}, new double[]{32.03, 34.93}));

        // מסלול אמצע-דרום - משולב
        runways.add(new Runway("RWY-3", Arrays.asList("Medium", "Large"),
                new double[]{31.99, 34.83}, new double[]{31.99, 34.93}));

        // מסלול דרומי - ענק
        runways.add(new Runway("RWY-4", Arrays.asList("Large"),
                new double[]{31.97, 34.83}, new double[]{31.97, 34.93}));
    }

    // פונקציית הטריגונומטריה: מחשבת את הזווית המדויקת מהמטוס אל קצה המסלול (נשארת כי addPlane משתמשת בה)
    private double calculateHeadingToTarget(double fromX, double fromY, double toX, double toY) {
        // מתמטיקה קלאסית: Y חלקי X
        double angleDeg = Math.toDegrees(Math.atan2(toY - fromY, toX - fromX));
        if (angleDeg < 0) {
            angleDeg += 360;
        }
        return angleDeg;
    }

    //  עדכון מטוס (נקרא ע"י ה-Socket)
    public void updatePlane(PlaneData data) {
        activePlanes.put(data.id, data);
    }

    //  שליפת כל המטוסים (ייקרא ע"י האתר והשירותים האחרים)
    public Collection<PlaneData> getAllPlanes() {
        return activePlanes.values();
    }

    //  הוספת מטוס חדש לרשימה (עבור המטוסים הידניים מהאתר)
    public void addPlane(PlaneData plane) {
        // עקיפה: מחשבים זווית ישירות לנתב"ג ודורסים את מה שהגיע מהאתר
        double targetToTLV = calculateHeadingToTarget(plane.getX(), plane.getY(), 32.01, 34.88);
        plane.setTargetHeading(targetToTLV);
        // אם המטוס נוצר קרוב (בתוך הרדאר), נגדיר אותו מיד לשיוט שיכנס למערכת
        plane.setState("CRUISE");

        activePlanes.put(plane.getId(), plane);
        System.out.println("✈️ Plane added manually: " + plane.getId());
    }

    // מחזירה כמה מטוסים אוטומטיים יש כרגע במערכת
    public int getAutoPlanesCount() {
        return (int) activePlanes.values().stream()
                .filter(PlaneData::isAutoGenerated) // סופר רק מטוסים עם התווית הדלוקה
                .count();
    }

    //  מחיקת מטוס (כשהוא נוחת/מתנתק/נמחק ע"י המשתמש)
    public void removePlane(String id) {
        activePlanes.remove(id);
    }

    // מאפשר למגדל הפיקוח לקרוא את מפת המטוסים המלאה (כדי למצוא מטוס ספציפי לפי ID בחירום)
    public Map<String, PlaneData> getActivePlanesMap() {
        return activePlanes;
    }

    // מאפשר למגדל הפיקוח לקרוא את רשימת המסלולים
    public List<Runway> getRunways() {
        return runways;
    }
}