package com.airguard.server.service;

import com.airguard.server.entity.Plane;
import org.springframework.stereotype.Service;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.beans.factory.annotation.Autowired;

@Service
public class TrafficGeneratorService {

    private final AirSpaceService airSpaceService;

    // הנה ההכנה לכפתור שביקשת! אם זה יהיה false, המערכת תפסיק לייצר מטוסים.
    private boolean isAutoSpawnEnabled = true;

    @Autowired
    public TrafficGeneratorService(AirSpaceService airSpaceService) {
        this.airSpaceService = airSpaceService;
    }

    // הטיימר: כל 3 שניות מנסה לייצר מטוס (אם הכפתור דלוק)
    @Scheduled(fixedRate = 15000)
    public void spawnRandomTraffic() {
        if (isAutoSpawnEnabled && airSpaceService.getAutoPlanesCount() < 5) {
            Plane newPlane = createRandomPlane();
            airSpaceService.addPlane(newPlane); // מעביר למחסן הראשי
        }
    }

    // הפונקציה שאחראית רק על הגרלת הנתונים
    private Plane createRandomPlane() {
        Plane plane = new Plane();
        String[] airlines = {"ELAL", "ARKIA", "ISRAIR", "LUFTHANSA", "WIZZ", "RYANAIR", "UNITED"};

        String randomAirline = airlines[(int) (Math.random() * airlines.length)];
        int flightNumber = 100 + (int) (Math.random() * 900); // מספר טיסה תלת-ספרתי
        plane.setId(randomAirline + "-" + flightNumber);

        double tlvX = 32.01;
        double tlvY = 34.88;
        double angle = Math.random() * 360;
        double radius = 0.3; // המרחק הקרוב שהגדרת

        // מיקום התחלתי
        plane.setX(tlvX + radius * Math.cos(Math.toRadians(angle)));
        plane.setY(tlvY + radius * Math.sin(Math.toRadians(angle)));

        // זווית טיסה ויעד
        plane.setHeading(Math.random() * 360);
        plane.setTargetHeading((angle + 180) % 360);

        // --- חישוב הגובה המקסימלי (Glide Slope) ביחס למרחק ---
        // משתמשים ברדיוס כבסיס לחישוב הגובה המקסימלי ההגיוני לאותו מרחק
        double maxAllowedAltitude = radius * 40000;
        double minAltitude = 3000; // לא נייצר מטוסים נמוך מ-3000 רגל כדי שיהיה להם זמן גישה

        // מוודאים שהתקרה לא נמוכה מהגובה המינימלי
        if (maxAllowedAltitude < minAltitude) {
            maxAllowedAltitude = minAltitude;
        }

        // הגרלת גובה הגיוני בתוך הטווח המותר
        double randomAltitude = minAltitude + (Math.random() * (maxAllowedAltitude - minAltitude));

        // נתונים אקראיים
        plane.setSpeed(700 + Math.random() * 200);
        plane.setAltitude(randomAltitude); // השורה שתוקנה
        plane.setEmergency(Math.random() < 0.15);

        // גודל
        double sizeRand = Math.random();
        if (sizeRand < 0.33) {
            plane.setSize("Small"); plane.setWeight(15);
        } else if (sizeRand < 0.66) {
            plane.setSize("Medium"); plane.setWeight(70);
        } else {
            plane.setSize("Large"); plane.setWeight(250);
        }

        plane.setFuel(20 + Math.random() * 80);

        plane.setAutoGenerated(true); // מסמן למערכת שזה מטוס שנוצר אוטומטית

        return plane;
    }

    // פונקציה שתאפשר לקונטרולר להדליק ולכבות את היצירה (עבור הכפתור ב-React)
    public void setAutoSpawnEnabled(boolean enabled) {
        this.isAutoSpawnEnabled = enabled;
    }

    public boolean isAutoSpawnEnabled() {
        return isAutoSpawnEnabled;
    }
}