package com.airguard.server.entity;

import jakarta.persistence.*;
import java.util.ArrayDeque;
import java.util.Deque;

@Entity
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "Planes")
public class Plane {

    // נתונים סטטיים (נשמרים בטבלת ה-SQL לתמיד)

    @Id
    @Column(name = "plane_id", length = 20)
    private String id; // נשאר id ב-Java כדי למנוע שגיאות קומפילציה בקוד הקיים

    private String model;

    @Column(name = "size_category")
    private String sizeCategory; // יישמר ב-DB כ-size_category (Small, Medium, Large)

    private double weight;

    @ManyToOne
    @JoinColumn(name = "airline_id")
    private Airline airline;

    // נתונים דינמיים (חיים רק ב-RAM, ה-SQL מתעלם מהם)
    @Transient public double x;
    @Transient public double y;
    @Transient public double fuel = 100.0;
    @Transient public double heading;
    @Transient private double speed;
    @Transient private double altitude;

    @Transient
    private Deque<double[]> pathHistory = new ArrayDeque<>();

    @Transient private boolean isEmergency = false;
    @Transient private String state = "CRUISE";
    @Transient private long spawnTime = System.currentTimeMillis();
    @Transient private double targetHeading;
    @Transient private String assignedRunway;
    @Transient private boolean isAutoGenerated;



    // קואורדינטות מרכז שדה התעופה לצורך חישובים בזמן אמת (במיקום של נתב"ג)
    @Transient private static final double TLV_X = 32.01;
    @Transient private static final double TLV_Y = 34.88;

    // בנאים (Constructors)

    public Plane() {
        // בנאי ריק עבור JPA ו-Hibernate
    }

    // לוגיקה עסקית ומכניקת טיסה

    // מחשב את המרחק של מטוס משדה התעופה
    public double getDistanceToAirport() {
        return Math.sqrt(Math.pow(this.x - TLV_X, 2) + Math.pow(this.y - TLV_Y, 2));
    }

    // מחשב את ציון העדיפות של המטוס
    public double calculatePriorityScore() {
        double score = 0;

        if (this.isEmergency) {
            score += 10000;
        }
        // "מרכך" הרעבה אפשרית של מטוס ב-Holding
        if (this.state.equals("HOLDING")) {
            score += 2000;
        }

        score += 1000.0 / Math.max(1.0, this.fuel);

        double distance = getDistanceToAirport();
        score += 500.0 / Math.max(0.01, distance);

        return score;
    }

    // גטרים וסטרים (Getters & Setters)

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    // תמיכה כפולה עבור הגודל - גם בפורמט ה-DB וגם בפורמט ה-UI הישן כדי ששום קובץ לא יישבר
    public String getSizeCategory() { return sizeCategory; }
    public void setSizeCategory(String sizeCategory) { this.sizeCategory = sizeCategory; }
    public String getSize() { return sizeCategory; }
    public void setSize(String size) { this.sizeCategory = size; }

    public double getWeight() { return weight; }
    public void setWeight(double weight) { this.weight = weight; }

    public Airline getAirline() { return airline; }
    public void setAirline(Airline airline) { this.airline = airline; }

    public double getX() { return x; }
    public void setX(double x) { this.x = x; }

    public double getY() { return y; }
    public void setY(double y) { this.y = y; }

    public double getFuel() { return fuel; }
    public void setFuel(double fuel) { this.fuel = fuel; }

    public double getHeading() { return heading; }
    public void setHeading(double heading) { this.heading = heading; }

    public double getSpeed() { return speed; }
    public void setSpeed(double speed) { this.speed = speed; }

    public double getAltitude() { return altitude; }
    public void setAltitude(double altitude) { this.altitude = altitude; }

    public Deque<double[]> getPathHistory() { return pathHistory; }
    public void setPathHistory(Deque<double[]> pathHistory) { this.pathHistory = pathHistory; }

    public boolean isEmergency() { return isEmergency; }
    public void setEmergency(boolean emergency) { this.isEmergency = emergency; }

    public String getState() { return state; }
    public void setState(String state) { this.state = state; }

    public long getSpawnTime() { return spawnTime; }
    public void setSpawnTime(long spawnTime) { this.spawnTime = spawnTime; }

    public double getTargetHeading() { return targetHeading; }
    public void setTargetHeading(double targetHeading) { this.targetHeading = targetHeading; }

    public String getAssignedRunway() { return assignedRunway; }
    public void setAssignedRunway(String assignedRunway) { this.assignedRunway = assignedRunway; }

    public boolean isAutoGenerated() { return isAutoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { isAutoGenerated = autoGenerated; }

    @Override
    public String toString() {
        return "Plane " + id + " at (" + (int)x + "," + (int)y + ") Fuel: " + fuel + "%";
    }
}