package com.airguard.server.model;
import java.util.ArrayDeque;
import java.util.Deque;

public class PlaneData {
    // השמות כאן חייבים להיות זהים בדיוק לשמות במחלקת Plane במטוס!
    public String id;
    public double x;
    public double y;
    public double fuel = 100.0;
    public double heading;
    private double speed;
    private double altitude;
    private String size;
    private double weight;
    // רשימה שתשמור את היסטוריית המיקומים [Latitude, Longitude]
    private Deque<double[]> pathHistory = new ArrayDeque<>();
    private boolean isEmergency = false;
    private String state = "CRUISE";
    private boolean isDeparting = false;
    private long spawnTime = System.currentTimeMillis();
    private double targetHeading; // לאן המטוס שואף להגיע
    private String assignedRunway;
    private boolean isAutoGenerated;

    // קואורדינטות מרכז נתב"ג (לצורך חישובי מרחק)
    private static final double TLV_X = 32.01;
    private static final double TLV_Y = 34.88;

    public double getDistanceToAirport() {
        return Math.sqrt(Math.pow(this.x - TLV_X, 2) + Math.pow(this.y - TLV_Y, 2));
    }

    // 2. חישוב ציון עדיפות לנחיתה (Priority Score)
    public double calculatePriorityScore() {
        // אם המטוס ממריא (על הקרקע), הציון שלו הוא פשוט כמה שניות הוא מחכה
        if (this.isDeparting) {
            long waitedSeconds = (System.currentTimeMillis() - this.spawnTime) / 1000;
            return waitedSeconds;
        }

        double score = 0;

        // חוק 1: מצב חירום מקבל בונוס פסיכי של 10,000 נקודות
        if (this.isEmergency) {
            score += 10000;
        }

        // חוק 2: דלק. ככל שיש פחות דלק, הציון עולה משמעותית.
        // משתמשים ב-Math.max כדי למנוע חלוקה באפס במקרה שנגמר הדלק לגמרי
        score += 1000.0 / Math.max(1.0, this.fuel);

        // חוק 3: מרחק. ככל שהמטוס קרוב יותר, הוא צריך לפנות את המרחב קודם.
        double distance = getDistanceToAirport();
        score += 500.0 / Math.max(0.01, distance);

        return score;
    }

    // Getters
    public String getId() {return id;}

    public double getX() {return x;}

    public double getY() {return y;}

    public double getFuel() {return fuel;}

    public double getHeading() {return heading;}

    public double getSpeed() {return speed;}

    public double getAltitude() {return altitude;}

    public String getSize() { return size; }

    public double getWeight() { return weight; }

    public Deque<double[]> getPathHistory() { return pathHistory; }

    public boolean isEmergency() {return isEmergency;}

    public String getState() { return state; }

    public boolean isDeparting() {return isDeparting;}

    public long getSpawnTime() {return spawnTime;}

    public double getTargetHeading() { return targetHeading; }

    public String getAssignedRunway() { return assignedRunway; }

    public boolean isAutoGenerated() { return isAutoGenerated; }


    // Setters
    public void setId(String id) {this.id = id;}

    public void setX(double x) {this.x = x;}

    public void setY(double y) {this.y = y;}

    public void setFuel(double fuel) {this.fuel = fuel;}

    public void setHeading(double heading) {this.heading = heading;}

    public void setSpeed(double speed) {this.speed = speed;}

    public void setAltitude(double altitude) {this.altitude = altitude;}

    public void setSize(String size) { this.size = size; }

    public void setWeight(double weight) { this.weight = weight; }

    public void setPathHistory(Deque<double[]> pathHistory) { this.pathHistory = pathHistory; }

    public void setEmergency(boolean emergency) {this.isEmergency = emergency;}

    public void setState(String state) { this.state = state; }

    public void setDeparting(boolean departing) {this.isDeparting = departing;}

    public void setSpawnTime(long spawnTime) { this.spawnTime = spawnTime; }

    public void setTargetHeading(double targetHeading) { this.targetHeading = targetHeading; }

    public void setAssignedRunway(String assignedRunway) { this.assignedRunway = assignedRunway; }

    public void setAutoGenerated(boolean autoGenerated) { isAutoGenerated = autoGenerated; }

    // אופציונלי: הדפסה נוחה כדי שנראה בלוגים מה קורה
    @Override
    public String toString() {
        return "Plane " + id + " at (" + (int)x + "," + (int)y + ") Fuel: " + fuel + "%";
    }
}